CREATE TABLE
  DISHES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    PRICE FLOAT,
    AVAILABLE INT,
    CATEGORY_ID INT,
    IMAGE_URL VARCHAR(100),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID)
  );